const inkDatabase = [
  {
    brand: "Wearingeul",
    name: "The Phantom at the Opera",
    colour: "Blue",
    shimmer: false,
    sheen: true,
    shading: "Low",
    sheenColour: "Red",
    shimmerColour: null,
  },
  {
    brand: "Wearingeul",
    name: "I Am a Cat",
    colour: "Grey",
    shimmer: true,
    sheen: false,
    shading: "Low",
    sheenColour: null,
    shimmerColour: "Gold",
  },
  // ==== Diamine inks ====
  {
    brand: "Diamine",
    name: "Burnt Sienna",
    colour: "Brown",
    shimmer: false,
    sheen: false,
    shading: "Medium",
    sheenColour: null,
    shimmerColour: null,
  },
  {
    brand: "Diamine",
    name: "Denim",
    colour: "Blue",
    shimmer: false,
    sheen: false,
    shading: "Medium",
    sheenColour: null,
    shimmerColour: null,
  },
  {
    brand: "Diamine",
    name: "Monboddo's Hat",
    colour: "Purple",
    shimmer: false,
    sheen: false,
    shading: "Low",
    sheenColour: null,
    shimmerColour: null,
  },
  {
    brand: "Diamine",
    name: "Vermillion",
    colour: "Red",
    shimmer: false,
    sheen: false,
    shading: "None",
    sheenColour: null,
    shimmerColour: null,
  },
  {
    brand: "Diamine",
    name: "Red Dragon",
    colour: "Red",
    shimmer: false,
    sheen: false,
    shading: "None",
    sheenColour: null,
    shimmerColour: null,
  },
  {
    brand: "Diamine",
    name: "Delamere Green",
    colour: "Green",
    shimmer: false,
    sheen: false,
    shading: "Medium",
    sheenColour: null,
    shimmerColour: null,
  },
  // ==== Octopus Fluids inks ==== 
  {
    brand: "Octopus Fluids",
    name: "Goblin",
    colour: "Green",
    shimmer: false,
    sheen: true,
    shading: "None",
    sheenColour: "Purple",
    shimmerColour: null,
  },
  {
    brand: "Octopus Fluids",
    name: "Dragon",
    colour: "Teal",
    shimmer: false,
    sheen: true,
    shading: "Medium",
    sheenColour: "Pink",
    shimmerColour: null,
  }
];